# zmodload zsh/zprof
plugins=(z git osx vi-mode per-directory-history dirhistory)

export ZSH_THEME="arrow"
export ZSH=~/.oh-my-zsh
source $ZSH/oh-my-zsh.sh
export EDITOR=nvim

export HISTCONTROL=ignorespace

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
bindkey '\e[3~' delete-char
# disable zsh autocompletion
setopt autolist
setopt noautomenu

export GOPATH=~/Development/Go
export GOBIN=~/Development/Go/bin

export PATH=$PATH:/usr/local/opt/go/libexec/bin
export PATH=$PATH:~/bin
export PATH=$PATH:/Applications/Tex/TeXShop.app/Contents/Resources/TeXShop/bin
export PATH=$GOBIN:/usr/local/bin:/usr/local/sbin:~/bin:$PATH
export PATH=$PATH:~/Development/flutter/bin:~/Development/flutter/bin/cache/dart-sdk/bin/
export PATH=$PATH:~/.pub-cache/bin

# yarn global packages
export PATH=$PATH:~/.config/yarn/global/node_modules/.bin

alias grep='ag'
alias gop='cd $GOPATH'
alias map="xargs -n1"
alias top="top -o cpu"
alias cd='cd -P'
alias vim=nvim

alias update='sudo softwareupdate -i -a; brew update; brew upgrade; brew cleanup; npm update npm -g; npm update -g; git -C ~/.dotfiles-ng pull --rebase'
alias afk="/System/Library/CoreServices/Menu\ Extras/User.menu/Contents/Resources/CGSession -suspend"
alias simulator='open /Applications/Xcode.app/Contents/Developer/Applications/Simulator.app'
alias vnc='open /System/Library/CoreServices/Applications/Screen\ Sharing.app/'
alias strace='sudo dtruss -t open_nocancel -p'
alias lsusb='system_profiler SPUSBDataType'
alias cat=bat

export TERM=screen-256color-bce
export SAVEHIST=10000
export HISTSIZE=10000
export HOMEBREW_NO_ANALYTICS=1

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

if [ "$TMUX" = "" ]; then
    tmux attach -t alacritty || tmux new -s alacritty
fi

export ANDROID_SDK_ROOT="/usr/local/share/android-sdk"
export ANDROID_HOME=${ANDROID_SDK_ROOT}
export PATH=$PATH:${ANDROID_SDK_ROOT}/tools
export PATH=$PATH:~/Development/flutter/bin
export PATH="/usr/local/opt/openjdk/bin:$PATH"
