#  zmodload zsh/zprof
plugins=(git osx vi-mode per-directory-history dirhistory)
export ZSH_THEME="geoffgarside"
export ZSH=~/.oh-my-zsh
source $ZSH/oh-my-zsh.sh

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# disable zsh autocompletion
setopt autolist
setopt noautomenu

export GOPATH=~/Development/Go
export GOBIN=~/Development/Go/bin

export PATH=$PATH:/usr/local/opt/go/libexec/bin
export PATH=$PATH:~/bin
export PATH=$GOBIN:/usr/local/bin:/usr/local/sbin:~/bin:$PATH

# yarn global packages
export PATH=$PATH:~/.config/yarn/global/node_modules/.bin

alias grep='ag'
alias gop='cd $GOPATH'
alias map="xargs -n1"
alias top="top -o cpu"
alias cd='cd -P'
alias vim=nvim

alias update='sudo softwareupdate -i -a; brew update; brew upgrade; brew cleanup; npm update npm -g; npm update -g; git -C ~/dotfiles pull --rebase'
alias afk="/System/Library/CoreServices/Menu\ Extras/User.menu/Contents/Resources/CGSession -suspend"
alias simulator='open /Applications/Xcode.app/Contents/Developer/Applications/Simulator.app'
alias vnc='open /System/Library/CoreServices/Applications/Screen\ Sharing.app/'
alias strace='sudo dtruss -t open_nocancel -p'
alias lsusb='system_profiler SPUSBDataType'

export TERM=screen-256color-bce
export SAVEHIST=10000
export HISTSIZE=10000
export HOMEBREW_NO_ANALYTICS=1
